app/src/main/AndroidManifest.xml, app/src/main/java/com/example/tiendadecampeones/ui/ProductsActivity.java, app/src/main/res/layout/activity_products.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/themes.xml
- Desarrollo funcional de barra de navegación lateral avanzado. 
- Renderizado dinámico de productos avanzado, simulé la entrega de datos desde el backend mediante un array con datos correspondientes a un modelo de producto.
=> Agrego desarrollo de actividad de productos

app/src/main/java/com/example/tiendadecampeones/ui/LoginActivity.java
soluciono error de tipeo en login  para poder correr la app
=> soluciono error de tipeo en login  para poder correr la app

app/src/main/java/com/example/tiendadecampeones/AboutUs.java, app/src/main/java/com/example/tiendadecampeones/Contacto.java, app/src/main/java/com/example/tiendadecampeones/ui/CountryProducts.java, app/src/main/java/com/example/tiendadecampeones/ui/ProductsActivity.java, app/src/main/java/com/example/tiendadecampeones/ui/Profile.java, app/src/main/res/layout/activity_about_us.xml, app/src/main/res/layout/activity_contacto.xml, app/src/main/res/layout/activity_products.xml, app/src/main/res/layout/product_card.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/themes.xml
Reverts Proyecto-integrador-ISPC-2024/proyecto-integrador-mobile-2024#84
=> Revert "Merge para arreglar conflictos en mi rama "

app/src/main/AndroidManifest.xml, app/src/main/java/com/example/tiendadecampeones/ui/CartResume.java, app/src/main/res/layout/activity_cart_resume.xml
Se añadió la pantalla de resumen de compra con su navegación desarrollada, faltaría traer los datos del carrito de compras
=> Vista resumen de compra

app/src/main/java/com/example/tiendadecampeones/ui/Dashboard.java, app/src/main/java/com/example/tiendadecampeones/ui/Profile.java, app/src/main/res/layout/activity_dashboard.xml, app/src/main/res/layout/activity_profile.xml, app/src/main/res/values/colors.xml
Actualizo funcionalidad de botones tanto profile como dashboard
=> agrego funcionalidad a botones que faltaban

app/src/main/AndroidManifest.xml, app/src/main/java/com/example/tiendadecampeones/ui/Dashboard.java, app/src/main/java/com/example/tiendadecampeones/ui/Profile.java
Soluciono redireccionamiento de boton finalizar sesion a Login.
=> soluciono boton de finalizar sesion

app/src/main/AndroidManifest.xml, app/src/main/java/com/example/tiendadecampeones/MainActivity.java, app/src/main/java/com/example/tiendadecampeones/ui/Dashboard.java, app/src/main/java/com/example/tiendadecampeones/ui/Home.java, app/src/main/java/com/example/tiendadecampeones/ui/MainActivity.java, app/src/main/res/layout/activity_dashboard.xml, app/src/main/res/layout/activity_home.xml, app/src/main/res/layout/activity_profile.xml
Readecuo el Dashboard y Profile y agrego  funcionalidad los botones de home para chequear navegabilidad
=> actualizo Dashboard y Profile

app/src/main/java/com/example/tiendadecampeones/ui/Home.java, app/src/main/res/layout/activity_cart.xml, app/src/main/res/layout/activity_home.xml
Readecuo el Dashboard y Profile y agrego  funcionalidad los botones de home para chequear navegabilidad
=> dejo establecidos los redireccionamientos de Home 

app/build.gradle.kts, app/src/main/AndroidManifest.xml, app/src/main/java/com/example/tiendadecampeones/models/Order.java, app/src/main/java/com/example/tiendadecampeones/ui/Dashboard.java, app/src/main/java/com/example/tiendadecampeones/ui/OrderActivity.java
Comento el código de Order.java, Dashboard.java, OrderActivity.java, AndroidManifest.xml (en relación con activity_order y activity_dashboard) para poder continuar trabajando
=> Comentado de código

app/src/main/AndroidManifest.xml, app/src/main/java/com/example/tiendadecampeones/ui/ManageProfile.java, app/src/main/java/com/example/tiendadecampeones/ui/Profile.java, app/src/main/res/layout/activity_home.xml, app/src/main/res/layout/activity_products.xml, app/src/main/res/layout/activity_profile.xml
Agrego desarrollo parcial de interfaz en ManageProfile.java y subo ajustes de interfaz en actividades de home, productos y perfil
=> Desarrollo y modificaciones en activities home, profile y products.

app/src/main/java/com/example/tiendadecampeones/ui/ManageProfile.java, app/src/main/res/layout/activity_edit_profile.xml, app/src/main/res/values/strings.xml
Desarrollo en activity_edit_profile.xml y su clase correspondiente.
=> Cristian recabarren

app/src/main/AndroidManifest.xml, app/src/main/java/com/example/tiendadecampeones/ui/CartResume.java
Agrego logs de debug en CartResume.java
=> Cristian recabarren | CartResume.java

app/build.gradle.kts, app/src/main/AndroidManifest.xml, app/src/main/java/com/example/tiendadecampeones/models/RegisterResponse.java, app/src/main/java/com/example/tiendadecampeones/network/ApiService.java, app/src/main/java/com/example/tiendadecampeones/ui/Register.java, app/src/main/res/layout/activity_register.xml, app/src/main/res/values/strings.xml, build.gradle.kts, gradle/libs.versions.toml
Se trabaja sobre las validaciones para el formulario registro
=> Jesica alvarez- Register.java

app/build.gradle.kts, app/src/main/java/com/example/tiendadecampeones/ui/LoginActivity.java
Ajusto detalles extra de código que no son relevantes
=> LoginActivity.java 

app/src/main/java/com/example/tiendadecampeones/adapters/CartAdapter.java, app/src/main/java/com/example/tiendadecampeones/adapters/ProductsAdapter.java, app/src/main/java/com/example/tiendadecampeones/ui/Cart.java
Se mejoró el envío del talle y cantidad de productos comprados al carrito
=> Se reparó el envío de talle y cantidad al carrito

app/src/main/java/com/example/tiendadecampeones/adapters/CartAdapter.java, app/src/main/java/com/example/tiendadecampeones/adapters/ProductsAdapter.java, app/src/main/java/com/example/tiendadecampeones/ui/Cart.java
Reverts Proyecto-integrador-ISPC-2024/proyecto-integrador-mobile-2024#203
=> Revert "Se reparó el envío de talle y cantidad al carrito"

app/src/main/java/com/example/tiendadecampeones/adapters/CartAdapter.java, app/src/main/java/com/example/tiendadecampeones/ui/Cart.java, app/src/main/java/com/example/tiendadecampeones/ui/OrderActivity.java, app/src/main/java/com/example/tiendadecampeones/ui/PaymentMethodsActivity.java
Se modificó el carrito de compras
=> Albano caminos

app/src/main/java/com/example/tiendadecampeones/adapters/CartAdapter.java, app/src/main/java/com/example/tiendadecampeones/ui/Cart.java, app/src/main/java/com/example/tiendadecampeones/ui/OrderActivity.java, app/src/main/java/com/example/tiendadecampeones/ui/PaymentMethodsActivity.java
Reverts Proyecto-integrador-ISPC-2024/proyecto-integrador-mobile-2024#205
=> Revert "Albano caminos"

app/src/main/java/com/example/tiendadecampeones/ui/Contact.java, app/src/main/res/layout/activity_contacto.xml, app/src/main/res/values/strings.xml
Agrego formulario en el archivo xml, validaciones en el archivo de java y los strings al archivo para el xml. Edité el contenido que se ve en la pantalla cambiando la información escrita de la tienda por el formulario
=> agrego formulario de contacto con validaciones implementadas

app/src/main/java/com/example/tiendadecampeones/ui/AboutUs.java, app/src/main/res/layout/activity_about_us.xml, app/src/main/res/layout/activity_home.xml, app/src/main/res/values/strings.xml
Se incorpora el botón que redirecciona a la pagina web ( en este caso será el repositorio de Git)
=> Se incorpora el boton para redireccionar a la pagina web

README.md, apk/apk-2024/nota.md, apk/apk-2025/nota.md, apk/nota.md
=>  subo apk + zip 2025
